-- Useful library included
--
local T = require("ccad.util.transform")
local B = require("ccad.util.box")
local S = require("ccad.util.sketch")

-- Project parameters
--

-- Generated by CodeCAD (pease change!)
--
local b = box(10, 10, 10)
emit(b)
